# syntax=docker/dockerfile:1
#
# Multi-stage Dockerfile for the Next.js (App Router) training app described in
# DESIGN.md. Standard `npm run build` + `npm start` on port 3000 — deliberately
# NOT assuming `output: "standalone"` in next.config, since that file isn't
# controlled here.
#
# NOTE: the "deps" and "build" stages assume package.json / package-lock.json
# already exist at the repo root when this image is built. Those are being
# generated by a separate `create-next-app` scaffolding pass happening in
# parallel with this file; this Dockerfile is written ahead of that work and
# is not expected to build successfully until the app scaffolding lands.

# ---- Dependencies ------------------------------------------------------------
FROM node:24-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# ---- Build ---------------------------------------------------------------
FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ---- Runtime ---------------------------------------------------------------
# No standalone output, so bring the whole built app (including full
# node_modules) forward from the builder stage rather than cherry-picking
# specific directories whose exact names/presence we don't want to assume.
FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app ./

USER nextjs
EXPOSE 3000

CMD ["npm", "start"]
